import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/componenets/themeProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased not-dark:bg-[#887baf]">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster />

          <div>{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
